version: '3.8'
services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?}
      POSTGRES_DB: ${POSTGRES_DB?}
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.node
    volumes:
      - staticdir:/usr/app/staticfiles

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile.django
    depends_on:
      - db
      - frontend
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DB_URL: ${DB_URL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      YANDEX_GEOCODER_API_KEY: ${YANDEX_GEOCODER_API_KEY}
      ROLLBAR_ACCESS_TOKEN: ${ROLLBAR_ACCESS_TOKEN?}
      ROLLBAR_ENVIRONMENT: ${ROLLBAR_ENVIRONMENT?}
    command: sh -c "python manage.py migrate --noinput && gunicorn -w 3 star_burger.wsgi:application --bind 0.0.0.0:8081"
    ports:
      - "8002:8000"
    volumes:
      - staticdir:/usr/app/staticfiles
      - mediadir:/usr/app/media
volumes:
  staticdir:
  mediadir:
  pg_data:
